In [79]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [80]:
# Reading Dataset and printing Dataset
data = pd.read_csv('toyota.csv')

In [81]:
#Dropping Duplicates
data.drop_duplicates()

model  year  price transmission  mileage fuelType  tax   mpg  \
0               GT86  2016  16000       Manual  24089.0   Petrol  265  36.2   
1               GT86  2017  15995       Manual  18615.0   Petrol  145  36.2   
2               GT86  2015  13998       Manual  27469.0   Petrol  265  36.2   
3               GT86  2017  18998       Manual  14736.0   Petrol  150  36.2   
4               GT86  2017  17498       Manual  36284.0   Petrol  145  36.2   
...              ...   ...    ...          ...      ...      ...  ...   ...   
6733              IQ  2011   5500    Automatic  30000.0   Petrol   20  58.9   
6734   Urban Cruiser  2011   4985       Manual  36154.0   Petrol  125  50.4   
6735   Urban Cruiser  2012   4995       Manual  46000.0   Diesel  125  57.6   
6736   Urban Cruiser  2011   3995       Manual  60700.0   Petrol  125  50.4   
6737   Urban Cruiser  2011   4495       Manual  45128.0   Petrol  125  50.4   

      engineSize  
0            2.0  
1            2.0  
2            2.0  
3            2.0  
4            2.0  
...          ...  
6733         1.0  
6734         1.3  
6735         1.4  
6736         1.3  
6737         1.3  

[6697 rows x 9 columns]

In [82]:
#check for missing Values
data.isnull().sum()

model             0
year              0
price             0
transmission      0
mileage         105
fuelType          0
tax               0
mpg               0
engineSize        0
dtype: int64

In [86]:
X = np.array(data[['model','year','transmission','mileage','fuelType','tax','mpg','engineSize']].values)
Y = np.array(data['price'].values)
print("X Values:\n",X)
print("Y Values:\n",Y)

X Values:
 [[' GT86' 2016 'Manual' ... 265 36.2 2.0]
 [' GT86' 2017 'Manual' ... 145 36.2 2.0]
 [' GT86' 2015 'Manual' ... 265 36.2 2.0]
 ...
 [' Urban Cruiser' 2012 'Manual' ... 125 57.6 1.4]
 [' Urban Cruiser' 2011 'Manual' ... 125 50.4 1.3]
 [' Urban Cruiser' 2011 'Manual' ... 125 50.4 1.3]]
Y Values:
 [16000 15995 13998 ...  4995  3995  4495]


In [87]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [88]:
im = SimpleImputer(missing_values=np.nan,strategy='mean')
im.fit(X[:,[3]])
X[:,[3]]=im.transform(X[:,[3]])
X=np.array(X)

In [92]:
print("Missing Values are in mileage:","\nBefore Removing Null Values:\n",data[0:10],"\nAfter removing Null Values:\n",X[0:10])

Missing Values are in mileage: 
Before Removing Null Values:
    model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual  24089.0   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual  18615.0   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual  27469.0   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual  14736.0   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual  36284.0   Petrol  145  36.2         2.0
5   GT86  2017  15998       Manual  26919.0   Petrol  260  36.2         2.0
6   GT86  2017  18522       Manual  10456.0   Petrol  145  36.2         2.0
7   GT86  2017  18995       Manual      NaN   Petrol  145  36.2         2.0
8   GT86  2020  27998       Manual    516.0   Petrol  150  33.2         2.0
9   GT86  2016  13990       Manual  37999.0   Petrol  265  36.2         2.0 
After removing Null Values:
 [[' GT86' 2016 'Manual' 24089.0 'Petrol' 265 36.2 2.0]
 [' GT86' 2017 'M

In [93]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
Lb = LabelEncoder()
Lb_1=LabelEncoder()
Lb_2 = LabelEncoder()
X[:,0]=Lb.fit_transform(X[:,0])
X[:,2]=Lb_1.fit_transform(X[:,2])
X[:,4]=Lb_2.fit_transform(X[:,4])

In [94]:
print("Encoding Categorical Data: model , transmission , fuel","\nBefore Encoding:\n",data[0:10],"\nAfter Encoding:\n",X[0:10])

Encoding Categorical Data: model , transmission , fuel 
Before Encoding:
    model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual  24089.0   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual  18615.0   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual  27469.0   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual  14736.0   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual  36284.0   Petrol  145  36.2         2.0
5   GT86  2017  15998       Manual  26919.0   Petrol  260  36.2         2.0
6   GT86  2017  18522       Manual  10456.0   Petrol  145  36.2         2.0
7   GT86  2017  18995       Manual      NaN   Petrol  145  36.2         2.0
8   GT86  2020  27998       Manual    516.0   Petrol  150  33.2         2.0
9   GT86  2016  13990       Manual  37999.0   Petrol  265  36.2         2.0 
After Encoding:
 [[6 2016 1 24089.0 3 265 36.2 2.0]
 [6 2017 1 18615.0 3 145 36.2 2.0]
 [

In [95]:
st = StandardScaler()
X=st.fit_transform(X)
st_1=StandardScaler()
Y=st_1.fit_transform([Y])

In [97]:
print("Before Normalizing:\n",data[0:10],"\nAfter Normalizing:\n",X[:10,:])

Before Normalizing:
    model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual  24089.0   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual  18615.0   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual  27469.0   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual  14736.0   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual  36284.0   Petrol  145  36.2         2.0
5   GT86  2017  15998       Manual  26919.0   Petrol  260  36.2         2.0
6   GT86  2017  18522       Manual  10456.0   Petrol  145  36.2         2.0
7   GT86  2017  18995       Manual      NaN   Petrol  145  36.2         2.0
8   GT86  2020  27998       Manual    516.0   Petrol  150  33.2         2.0
9   GT86  2016  13990       Manual  37999.0   Petrol  265  36.2         2.0 
After Normalizing:
 [[-0.30818359 -0.3394643   0.47861718  0.06468624  0.77723245  2.30527356
  -1.6950626   1.2122702 ]
 [-0.30818359  0.1142