# DIGITAL ASSIGNMENT -  4
# SUBJECT : MACHINE LEARNING FUNDAMENTALS
# COURSE CODE : ECE3047
# SLOT : L35+L36






# NAME : P SAI DHEERAJ
# REG NUM : 18BIS0068



In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [12]:
data = pd.read_csv('College.csv')
data.head()

College Private  Apps  Accept  Enroll  Top10perc  \
0  Abilene Christian University     Yes  1660    1232     721         23   
1            Adelphi University     Yes  2186    1924     512         16   
2                Adrian College     Yes  1428    1097     336         22   
3           Agnes Scott College     Yes   417     349     137         60   
4     Alaska Pacific University     Yes   193     146      55         16   

   Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  \
0         52         2885          537      7440        3300    450      2200   
1         29         2683         1227     12280        6450    750      1500   
2         50         1036           99     11250        3750    400      1165   
3         89          510           63     12960        5450    450       875   
4         44          249          869      7560        4120    800      1500   

   PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0   70        78       18.1           12    7041         60  
1   29        30       12.2           16   10527         56  
2   53        66       12.9           30    8735         54  
3   92        97        7.7           37   19016         59  
4   76        72       11.9            2   10922         15

In [13]:
data = data.drop(['College'],axis=1)
from sklearn.preprocessing import LabelEncoder
lb_private = LabelEncoder()
data['Private'] = lb_private.fit_transform(data['Private'])
data.head()

Private  Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  \
0        1  1660    1232     721         23         52         2885   
1        1  2186    1924     512         16         29         2683   
2        1  1428    1097     336         22         50         1036   
3        1   417     349     137         60         89          510   
4        1   193     146      55         16         44          249   

   P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
0          537      7440        3300    450      2200   70        78   
1         1227     12280        6450    750      1500   29        30   
2           99     11250        3750    400      1165   53        66   
3           63     12960        5450    450       875   92        97   
4          869      7560        4120    800      1500   76        72   

   S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0       18.1           12    7041         60  
1       12.2           16   10527         56  
2       12.9           30    8735         54  
3        7.7           37   19016         59  
4       11.9            2   10922         15

In [14]:
corr = data.corr()
corr


Private      Apps    Accept    Enroll  Top10perc  Top25perc  \
Private      1.000000 -0.432095 -0.475252 -0.567908   0.164132   0.095752   
Apps        -0.432095  1.000000  0.943451  0.846822   0.338834   0.351640   
Accept      -0.475252  0.943451  1.000000  0.911637   0.192447   0.247476   
Enroll      -0.567908  0.846822  0.911637  1.000000   0.181294   0.226745   
Top10perc    0.164132  0.338834  0.192447  0.181294   1.000000   0.891995   
Top25perc    0.095752  0.351640  0.247476  0.226745   0.891995   1.000000   
F.Undergrad -0.615561  0.814491  0.874223  0.964640   0.141289   0.199445   
P.Undergrad -0.452088  0.398264  0.441271  0.513069  -0.105356  -0.053577   
Outstate     0.552650  0.050159 -0.025755 -0.155477   0.562331   0.489394   
Room.Board   0.340532  0.164939  0.090899 -0.040232   0.371480   0.331490   
Books       -0.018549  0.132559  0.113525  0.112711   0.118858   0.115527   
Personal    -0.304485  0.178731  0.200989  0.280929  -0.093316  -0.080810   
PhD         -0.156714  0.390697  0.355758  0.331469   0.531828   0.545862   
Terminal    -0.129620  0.369491  0.337583  0.308274   0.491135   0.524749   
S.F.Ratio   -0.472205  0.095633  0.176229  0.237271  -0.384875  -0.294629   
perc.alumni  0.414775 -0.090226 -0.159990 -0.180794   0.455485   0.417864   
Expend       0.258461  0.259592  0.124717  0.064169   0.660913   0.527447   
Grad.Rate    0.336162  0.146755  0.067313 -0.022341   0.494989   0.477281   

             F.Undergrad  P.Undergrad  Outstate  Room.Board     Books  \
Private        -0.615561    -0.452088  0.552650    0.340532 -0.018549   
Apps            0.814491     0.398264  0.050159    0.164939  0.132559   
Accept          0.874223     0.441271 -0.025755    0.090899  0.113525   
Enroll          0.964640     0.513069 -0.155477   -0.040232  0.112711   
Top10perc       0.141289    -0.105356  0.562331    0.371480  0.118858   
Top25perc       0.199445    -0.053577  0.489394    0.331490  0.115527   
F.Undergrad     1.000000     0.570512 -0.215742   -0.068890  0.115550   
P.Undergrad     0.570512     1.000000 -0.253512   -0.061326  0.081200   
Outstate       -0.215742    -0.253512  1.000000    0.654256  0.038855   
Room.Board     -0.068890    -0.061326  0.654256    1.000000  0.127963   
Books           0.115550     0.081200  0.038855    0.127963  1.000000   
Personal        0.317200     0.319882 -0.299087   -0.199428  0.179295   
PhD             0.318337     0.149114  0.382982    0.329202  0.026906   
Terminal        0.300019     0.141904  0.407983    0.374540  0.099955   
S.F.Ratio       0.279703     0.232531 -0.554821   -0.362628 -0.031929   
perc.alumni    -0.229462    -0.280792  0.566262    0.272363 -0.040208   
Expend          0.018652    -0.083568  0.672779    0.501739  0.112409   
Grad.Rate      -0.078773    -0.257001  0.571290    0.424942  0.001061   

             Personal       PhD  Terminal  S.F.Ratio  perc.alumni    Expend  \
Private     -0.304485 -0.156714 -0.129620  -0.472205     0.414775  0.258461   
Apps         0.178731  0.390697  0.369491   0.095633    -0.090226  0.259592   
Accept       0.200989  0.355758  0.337583   0.176229    -0.159990  0.124717   
Enroll       0.280929  0.331469  0.308274   0.237271    -0.180794  0.064169   
Top10perc   -0.093316  0.531828  0.491135  -0.384875     0.455485  0.660913   
Top25perc   -0.080810  0.545862  0.524749  -0.294629     0.417864  0.527447   
F.Undergrad  0.317200  0.318337  0.300019   0.279703    -0.229462  0.018652   
P.Undergrad  0.319882  0.149114  0.141904   0.232531    -0.280792 -0.083568   
Outstate    -0.299087  0.382982  0.407983  -0.554821     0.566262  0.672779   
Room.Board  -0.199428  0.329202  0.374540  -0.362628     0.272363  0.501739   
Books        0.179295  0.026906  0.099955  -0.031929    -0.040208  0.112409   
Personal     1.000000 -0.010936 -0.030613   0.136345    -0.285968 -0.097892   
PhD         -0.010936  1.000000  0.849587  -0.130530     0.249009  0.432762   
Terminal    -0.030613  0.849587  1.000000  -0.160104    

In [15]:
ind = np.where(corr>0.7)
ind = np.array(ind)
del_ind = []
for i in range(0,34):
    if ind[0,i]>ind[1,i]:
        del_ind.append(ind[1,i])
del_ind = np.unique(np.array(del_ind))
print(del_ind)
data = np.array(data)
data = np.delete(data,del_ind,axis=1)
data = data.astype(int)


[ 1  2  3  4 12]
[[ 0  1  1  1  1  2  2  2  2  3  3  3  3  4  4  5  5  6  6  6  6  7  8  9
  10 11 12 12 13 13 14 15 16 17]
 [ 0  1  2  3  6  1  2  3  6  1  2  3  6  4  5  4  5  1  2  3  6  7  8  9
  10 11 12 13 12 13 14 15 16 17]]


In [8]:
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte = train_test_split(data[:,1:],data[:,0])
data

array([[    1,    52,  2885, ...,    12,  7041,    60],
       [    1,    29,  2683, ...,    16, 10527,    56],
       [    1,    50,  1036, ...,    30,  8735,    54],
       ...,
       [    1,    61,  2793, ...,    20,  8323,    49],
       [    1,    99,  5217, ...,    49, 40386,    99],
       [    1,    63,  2988, ...,    28,  4509,    99]])

In [9]:
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix
kmeans = KMeans(n_clusters = 2)
kmeans.fit(xtr)

KMeans(n_clusters=2)

In [62]:
y_pred = kmeans.predict(xte)
# print(np.concatenate((y_pred.reshape(len(y_pred),1),yte.reshape(len(y_pred),1)),axis=1))
cf = confusion_matrix(y_pred,yte)
cf

array([[  1,  36],
       [ 52, 106]], dtype=int64)

In [63]:
precision = (cf[0][0]/(cf[0][0]+cf[0][1]))
recall = (cf[0][0]/(cf[0][0]+cf[1][0]))
f1 = 2*precision*recall/(precision+recall)
accuracy = 100*(cf[0][0]+cf[1][1])/(cf[0][0]+cf[1][1]+cf[0][1]+cf[1][0])

In [64]:
print("Accuracy is: %.2f\nPrecision is: %.2f\nRecall is: %.2f\nF1_Score is: %.2f"%(accuracy,precision,recall,f1))

Accuracy is: 54.87
Precision is: 0.03
Recall is: 0.02
F1_Score is: 0.02


In [65]:
from sklearn.cluster import AgglomerativeClustering
agg = AgglomerativeClustering(n_clusters = 2)  #Hierarchical Clustering
agg.fit(xtr)

AgglomerativeClustering()

In [66]:
y_pred = agg.fit_predict(xte)
# print(np.concatenate((y_pred.reshape(len(y_pred),1),yte.reshape(len(y_pred),1)),axis=1))
cf = confusion_matrix(y_pred,yte)
cf

array([[ 53, 112],
       [  0,  30]], dtype=int64)

In [67]:
precision = (cf[0][0]/(cf[0][0]+cf[0][1]))
recall = (cf[0][0]/(cf[0][0]+cf[1][0]))
f1 = 2*precision*recall/(precision+recall)
accuracy = 100*(cf[0][0]+cf[1][1])/(cf[0][0]+cf[1][1]+cf[0][1]+cf[1][0])
print("Accuracy is: %.2f\nPrecision is: %.2f\nRecall is: %.2f\nF1_Score is: %.2f"%(accuracy,precision,recall,f1))

Accuracy is: 42.56
Precision is: 0.32
Recall is: 1.00
F1_Score is: 0.49


In [59]:
from sklearn.cluster import SpectralClustering
spec = SpectralClustering(n_clusters = 2,assign_labels='discretize',random_state=0)
spec.fit(xtr)

C:\Users\dheer\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:245: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"


SpectralClustering(assign_labels='discretize', n_clusters=2, random_state=0)

In [68]:
y_pred = spec.fit_predict(xte)
# print(np.concatenate((y_pred.reshape(len(y_pred),1),yte.reshape(len(y_pred),1)),axis=1))
cf = confusion_matrix(y_pred,yte)
cf

C:\Users\dheer\anaconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:245: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"


array([[25, 79],
       [28, 63]], dtype=int64)

In [69]:
precision = (cf[0][0]/(cf[0][0]+cf[0][1]))
recall = (cf[0][0]/(cf[0][0]+cf[1][0]))
f1 = 2*precision*recall/(precision+recall)
accuracy = 100*(cf[0][0]+cf[1][1])/(cf[0][0]+cf[1][1]+cf[0][1]+cf[1][0])
print("Accuracy is: %.2f\nPrecision is: %.2f\nRecall is: %.2f\nF1_Score is: %.2f"%(accuracy,precision,recall,f1))

Accuracy is: 45.13
Precision is: 0.24
Recall is: 0.47
F1_Score is: 0.32
